# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
  # No gaps between windows
  # gaps_in = 0
  # gaps_out = 0

  # Use master layout instead of dwindle
  # layout = master

  layout = scrolling
  gaps_out = 2,10,10,10
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
  # Use round window corners
  rounding = 8
  active_opacity = 0.8
  inactive_opacity = 0.6
  blur {
      passes = 4
      popups = true
  }
}

scrolling {
  column_width = 0.5
}

windowrule = match:class Alacritty, opacity 0.65 0.5

bezier = hmm, 0.68, -0.55, 0.27, 1.55
animation = workspaces, 1, 5, hmm, slidefade
animation = windows, 1, 5, hmm, slide
animation = layers, 1, 5, hmm, slide
animation = fade, 1, 10, hmm
animation = monitorAdded, 1, 10, hmm
